import java.awt.image.*;
import javax.imageio.*;
import javax.swing.*;
import java.io.*;
import java.net.URL;
import java.util.*;
import java.util.concurrent.atomic.AtomicReference;

public class Steganography extends AES {

  public Steganography(String key) {
    super(key);
}

	// embed the message into an image
	public static BufferedImage embedText(BufferedImage image, String text) {
                StringBuilder word = new StringBuilder(text);
                //Add a delimiter for the message
                word.append("}");
                text = word.toString();
		int bitMsk = 0x00000001;	// bit mask to get the digits
		int bit;				// integer that represents the ASCII of a character
		int x = 0;				// starting x pixel
		int y = 0;				// starting y pixel
		int txtLen = text.length();
		for(int i = 0; i < txtLen; i++) {			
			bit = (int) text.charAt(i);		// get the ASCII of a character at position i
			for(int j = 0; j < 8; j++) {
				int flag = bit & bitMsk;	// get 1 digit from the character
				if(flag == 1) {	
					if(x < image.getWidth()) {
						image.setRGB(x, y, image.getRGB(x, y) | 0x00000001); 	// store the 1 bit into a pixel's last digit
						x++;
					}
					else {
						x = 0;
						y++;
						image.setRGB(x, y, image.getRGB(x, y) | 0x00000001); 	// store the 1 bit into a pixel's last digit
					}
				} 
				else {	
					if(x < image.getWidth()) {
						image.setRGB(x, y, image.getRGB(x, y) & 0xFFFFFFFE);	// store the 0 bit into a pixel's last digit
						x++;
					}
					else {
						x = 0;
						y++;
						image.setRGB(x, y, image.getRGB(x, y) & 0xFFFFFFFE);	// store the 0 bit into a pixel's last digit
					}
				}
				bit = bit >> 1;				// get the next digit
			}			
		}
		
		// save the image which contains the text to a new image file
		try {
			File outFile = new File("textEmbedded.png");	
			ImageIO.write(image, "png", outFile);	
		} catch (IOException e) {
			
		}		
		return image;
	}
        
	// extract and decrypt the message from an image
	public static void extractText(BufferedImage image, String uKey) throws Exception {
		System.out.print("Extracting: ");
		/**
		 * [START] Variables for extractText method
		 */
		// Integer variables
		int bitMsk = 0x00000001;	// bit mask to get the digits
		int x = 0;					// starting x pixel
		int y = 0;					// starting y pixel
		int flag;
		// Char variables
		List<Character> c = new ArrayList<Character>();	// Array to store the message extracted from the image character by character
		// String variables
		StringBuilder word = new StringBuilder(""); // String to append the characters of variable 'c' in order to build the message
		String decode = ""; // String to parse the 'word' StringBuilder object
		String decData = ""; //String to store the decoded message generated by AES decryption
		// AES variable
		AES aesDec = new AES(uKey); // Create an AES object passing the key as a parameter
		/**
		 * [END] Variables for extractText method
		 */
                
                //A single digit is extracted for comparison
                int bit = 0;
			
			// 8 digits form a character
			for(int j = 0; j < 8; j++) {				
				if(x < image.getWidth()) {
					flag = image.getRGB(x, y) & bitMsk;	// get the last digit of the pixel
					x++;
				}
				else {
					x = 0;
					y++;
					flag = image.getRGB(x, y) & bitMsk;	// get the last digit of the pixel
				}
				
				// store the extracted digits into an integer as ASCII
				if(flag == 1) {					
					bit = bit >> 1;	
					bit = bit | 0x80;
				} 
				else {					
					bit = bit >> 1;
				}				
			}
			c.add((char) bit);	// Parse the ASCII to characters
			word.append(c.get(0)); // Append characters to the word StringBuilder
                        
                        //System.out.println(word.toString());
                     
                //The rest of the string is extracted
                int i = 0;
		while(word.toString().charAt(i) != '}') {
			
			for(int j = 0; j < 8; j++) {				
				if(x < image.getWidth()) {
					flag = image.getRGB(x, y) & bitMsk;
					x++;
				}
				else {
					x = 0;
					y++;
					flag = image.getRGB(x, y) & bitMsk;
				}
				
				if(flag == 1) {					
					bit = bit >> 1;	
					bit = bit | 0x80;
				} 
				else {					
					bit = bit >> 1;
				}				
			}
			c.add((char) bit);
			word.append(c.get(i));
                        i++;
		}
                
                //Delete the duplicate character
                word.deleteCharAt(0);
                //Delete the delimiter
                word.deleteCharAt(word.length()-1);
                
		decode = word.toString(); // Convert StringBuilder object to String type
		decData = aesDec.decryptAES(decode); // Decrypt message using AES
		System.out.println("Message was decrypted succesfully!");
		System.out.println("...");            
		System.out.println("The message is: " + decData);
		System.out.println("");
	}
	
	public static void main(String[] args) {
		/**
	 	* [START] Variables for extractText method
		*/
		// Integer for menu options
		int op;	
		AtomicReference<String> s = new AtomicReference<>(); // An atomic reference to a variable for the name of the image file which can be modified anywhere
		// Scanner variable
		Scanner sc = new Scanner(System.in);
		// String variables
		String uKey = ""; // String to store the 16 character key given by the user
		String msg = ""; // String to store the message to hide
		String encData = ""; // String to store the hidden message (encrypted with AES)
		/**
	 	* [END] Variables for extractText method
		*/
		BufferedImage originalImageText = null; //Original unaltered image
		BufferedImage coverImageText = null; //Image to embed the secret message
                
                try {
                    do {
                        menu();
                        op = sc.nextInt();
                        sc.nextLine();
                        switch (op) {
                            case 1:
                                try {
                                    URL path = Steganography.class.getResource("cover.jpg");
                                    originalImageText = ImageIO.read(new File(path.getFile()));
                                    coverImageText = ImageIO.read(new File(path.getFile()));
                                    System.out.print("Embedding: ");
                                    // [START] AES Part
                                    System.out.println("Please enter a 16 character key: ");
                                    uKey = sc.nextLine(); // Input key
                                    // Check if the key size is 16 character length
                                    while (checkKey(uKey) != true) {
					uKey = sc.nextLine();
                                    }
                                    // Create AES object passing the user defined key as a parameter
                                    AES aesEnc = new AES(uKey);
                                    System.out.println("Please write a message to hide: ");
                                    msg = sc.nextLine(); // Input message
                                    encData = aesEnc.encryptAES(msg); // Encode data
                                    System.out.println("Message was encrypted succesfully!");
                                    System.out.println("The message is: " + encData);
                                    // [END] AES Part																
                                    s.set(encData);
                                    coverImageText = embedText(coverImageText, s.get());  // embed the encrypted message to the image
                                    JFrame frame = new JFrame("Text Steganography");
                                    JPanel panel = new JPanel();
                                    JLabel label1 = new JLabel(new ImageIcon(originalImageText));
                                    JLabel label2 = new JLabel(new ImageIcon(coverImageText));
                                    panel.add(label1);
                                    panel.add(label2);
                                    frame.add(panel);
                                    frame.pack();
                                    frame.setVisible(true);
                                    System.out.println("Message embedded!");
                                } catch(IOException e) {		
                                    System.out.println("Image not found");
                                }
                                break;
                            case 2:
                                try {
                        
                                    URL path = Steganography.class.getResource("cover.jpg");
                                    originalImageText = ImageIO.read(new File(path.getFile()));
                                    coverImageText = ImageIO.read(new File(path.getFile()));

									// extract and decrypt the message
                                    System.out.println("Please enter the 16 character key: ");
                                    uKey = sc.nextLine();
                                    while (checkKey(uKey) != true) {
										uKey = sc.nextLine();
                                    }
                                    extractText(ImageIO.read(new File("textEmbedded.png")), uKey);		
                                } catch(IOException e) {		
                                    System.out.println("Image not found");
                                }
                                break;                
                            default:
                                System.exit(0);
                        }
                    } while (op != 3);

                } catch (Exception e) {
                    //System.out.println("System error!");
					e.printStackTrace();
                }
		sc.close();	
	}
        
        public static void menu() {
            System.out.println("==============================");
            System.out.println("Welcome to GunmetalCypher v0.1");
            System.out.println("Stegosaurus Special Edition!");
            System.out.println("==============================");
            System.out.println("\n");
            System.out.println("1. Embed message");
            System.out.println("2. Extract message");
            System.out.println("3. Exit");
            System.out.print("Option: ");
        }
        
	public static boolean checkKey(String uKey) {
            if (uKey.length() == 16) {
		System.out.println("Key - OK!");
		return true;
            } else {
		return false;
            }
	}
}